#!/usr/bin/env sh

# Run lint with the custom ESLint config but don't fail if there are warnings
echo "Running lint..."
pnpm lint || echo "Linting had issues, but we'll continue with the commit"

# Run formatting but don't fail if there are issues
echo "Running format..."
pnpm format || echo "Formatting had issues, but we'll continue with the commit"

exit 0
